In [1]:
##Importamos librerias 

import pandas as pd
import numpy as np
import requests

pd.set_option('display.max_columns', None)

In [ ]:
## DF OMOPHOBIA: 
## Fuente:

In [31]:
df_omophobia = pd.read_csv('/mnt/c/Users/arian/Documents/Adalab/Modulo 4/proyecto-da-promo-k-modulo-4-team-3/files/omophobia.csv', encoding="latin1", delimiter=";")
df_omophobia.head(10)

,COUNTRY,CSSSA LEGAL?,DATE OF DECRIM,MAX PENALTY,CONST.,BROAD PROT.,EMPLOY.,HATE CRIME,INCITEMENT,BAN CONV. THERAPIES,SAME SEX MARRIAGE,CIVIL UNIONS,JOINT ADOPTION,SECOND PARENT ADOPTION
0,Algeria,NO,-,2,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
1,Angola,YES,2021,-,NO,YES,YES,YES,YES,NO,NO,NO,NO,NO
2,Benin,YES,NEVER CRIM,-,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
3,Botswana,YES,2019,-,NO,NO,YES,NO,NO,NO,NO,NO,NO,NO
4,Burkina Faso,YES,NEVER CRIM,-,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
5,Burundi,NO,-,2,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
6,Cameroon,NO,-,5,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
7,Cabo Verde,YES,2004,-,NO,NO,YES,YES,NO,NO,NO,NO,NO,NO
8,Central Africa Republic,YES,NEVER CRIM,-,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO
9,Chad,NO,-,2,NO,NO,NO,YES,NO,NO,NO,NO,NO,NO

In [7]:
df_omophobia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   COUNTRY                 241 non-null    object
 1   CSSSA LEGAL?            241 non-null    object
 2   DATE OF DECRIM          240 non-null    object
 3   MAX PENALTY             241 non-null    object
 4   CONST.                  197 non-null    object
 5   BROAD PROT.             241 non-null    object
 6   EMPLOY.                 241 non-null    object
 7   HATE CRIME              241 non-null    object
 8   INCITEMENT              241 non-null    object
 9   BAN CONV. THERAPIES     241 non-null    object
 10  SAME SEX MARRIAGE       241 non-null    object
 11  CIVIL UNIONS            241 non-null    object
 12  JOINT ADOPTION          241 non-null    object
 13  SECOND PARENT ADOPTION  241 non-null    object
dtypes: object(14)
memory usage: 26.5+ KB

In [ ]:
## DF RAINBOW
## Fuente: https://rainbowmap.ilga-europe.org/

In [9]:
df_rainbow_map = pd.read_csv('/mnt/c/Users/arian/Documents/Adalab/Modulo 4/proyecto-da-promo-k-modulo-4-team-3/files/2024-rainbow-map-data.csv', index_col=0)
df_rainbow_map.head(4)

,COUNTRIES,RANKING,Equality & non-discrimination,Equality & non-discrimination.1,Equality & non-discrimination.2,Equality & non-discrimination.3,Equality & non-discrimination.4,Equality & non-discrimination.5,Equality & non-discrimination.6,Equality & non-discrimination.7,Equality & non-discrimination.8,Equality & non-discrimination.9,Equality & non-discrimination.10,Equality & non-discrimination.11,Equality & non-discrimination.12,Equality & non-discrimination.13,Equality & non-discrimination.14,Equality & non-discrimination.15,Equality & non-discrimination.16,Equality & non-discrimination.17,Equality & non-discrimination.18,Equality & non-discrimination.19,Equality & non-discrimination.20,Equality & non-discrimination.21,Equality & non-discrimination.22,Equality & non-discrimination.23,Equality & non-discrimination.24,Family,Family.1,Family.2,Family.3,Family.4,Family.5,Family.6,Family.7,Family.8,Family.9,Family.10,Hate crime & hate speech,Hate crime & hate speech.1,Hate crime & hate speech.2,Hate crime & hate speech.3,Hate crime & hate speech.4,Hate crime & hate speech.5,Hate crime & hate speech.6,Hate crime & hate speech.7,Legal gender recognition,Legal gender recognition.1,Legal gender recognition.2,Legal gender recognition.3,Legal gender recognition.4,Legal gender recognition.5,Legal gender recognition.6,Legal gender recognition.7,Legal gender recognition.8,Legal gender recognition.9,Legal gender recognition.10,Legal gender recognition.11,Legal gender recognition.12,Legal gender recognition.13,Legal gender recognition.14,Intersex bodily integrity,Intersex bodily integrity.1,Intersex bodily integrity.2,Intersex bodily integrity.3,Civil society space,Civil society space.1,Civil society space.2,Civil society space.3,Civil society space.4,Civil society space.5,Asylum,Asylum.1,Asylum.2,Asylum.3,Asylum.4,Asylum.5
ABR,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
NaN,NaN,NaN,Constitution (sexual orientation),Employment (sexual orientation),Goods & services (sexual orientation),Education (sexual orientation),Health (sexual orientation),Conversion practices ban (sexual orientation),Equality body mandate (sexual orientation),Equality action plan (sexual orientation),Constitution (gender identity),Employment (gender identity),Goods & services (gender identity),Education (gender identity),Health (gender identity),Conversion practices ban (gender identity),Equality body mandate (gender identity),Equality action plan (gender identity),Law (gender expression),Constitution (sex characteristics),Employment (sex characteristics),Goods & services (sex characteristics),Education (sex characteristics),Health (sex characteristics),Equality body mandate (sex characteristics),Equality action plan (sex characteristics),Blood donations,Marriage equality,Registered partnership (similar rights to marr...,Registered partnership (limited rights),Cohabitation,No constitutional limitation on marriage,Joint adoption,Second-parent adoption,Automatic co-parent recognition,Medically assisted insemination (couples),Medically assisted insemination (singles),Recognition of trans parenthood,Hate crime law (sexual orientation),Hate speech law (sexual orientation),Policy tackling hatred (sexual orientation),Hate crime law (gender identity),Hate speech law (gender identity),Policy tackling hatred (gender identity),Hate crime law (intersex),Policies tackling hatred (intersex),No legal framework making legal gender recogni...,Existence of legal measures,Existence of administrative procedures,Name change,"No age restriction, Name change",Self-determination,Non-binary recognition,No 'Gender Identity Disorder' diagnosis/psycho...,No compulsory medical intervention required,No compulsory surgical intervention required,No compulsory sterilisation required,No compulsory divorce required,No age restriction,Legal gender recognition procedures exist for ...,Depathologisation,Prohibition of medical intervention without in...,Universality of prohibition of medical interve...,Existence of effective monitoring mechanism,Access to justice for victims and reparations,"Public event held, no state obstruction of fre...","Public event held, there is enough protection ...","Associations operate, no state obstruction of ...",LGBTI human rights defenders are not at risk,No laws limiting external funding,No laws limiting freedom of expression (nation...,Asylum law (sexual orientation),Other positive measures (sexual orientation),Asylum law (gender identity),Other positive measures (gender identity),Asylum law (intersex),Other positive measures (intersex)
NaN,NaN,NaN,"0,16%","1,10%","1,10%","1,10%","1,10%","0,80%","0,78%","0,88%","0,16%","1,10%","1,10%","1,10%","1,10%","0,80%","0,78%","0,88%","1,83%","0,16%","1,10%","1,10%","1,10%","1,10%","0,78%","0,88%","0,91%","3,75%","3,00%","2,00%","1,00%","0,75%","3,00%","1,75%","1,75%","2,00%","2,00%","2,50%","2,43%","2,43%","2,28%","2,43%","2,43%","2,28%","2,43%","2,28%","0,75%","1,50%","1,00%","1,00%","0,15%","2,00%","1,00%","1,75%","1,15%","1,15%","1,70%","1,05%","1,00%","0,30%","2,00%","2,50%","0,50%","1,00%","1,00%","1,50%","1,50%","1,50%","1,50%","1,50%","1,50%","1,50%","1,50%","1,50%","1,50%","1,50%","1,50%"
AL,Albania,"36,38",0,1,1,1,0,0,1,0,0,1,1,1,0,0,1,0,0,0,1,1,1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,1,1,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,0,1,0,0,0
AD,Andorra,"43,23",1,1,1,1,1,0,1,0,0,1,1,1,1,0,1,0,1,0,0,0,0,0,0,0,0,1,1,1,0,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,1,1,0,0,1,1,1,1,1,0,0,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,0,0

In [11]:
df_rainbow_map.shape

(51, 77)

In [12]:
df_rainbow_map['COUNTRIES'].count()

49

In [13]:
df_1 = pd.read_excel('/mnt/c/Users/arian/Documents/Adalab/Modulo 4/proyecto-da-promo-k-modulo-4-team-3/files/_database_digital_rev.4_7_21.xlsx')
df_1

,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10,Column11,Column12,Column13,Column14,Column15,Column16,Column17,Column18,Column20,Column21,Column22,Column23,Column24,Column25,Column26,Column27,Column28,Column29,Column30,Column31
0,continent,sub contient,country,Predom. Religion,SOGI-LI,DEMOC.,HAPPINESS,Per capita GDP,% with tertiary educ.,GRI,Religiosity,SHI,legality of sam-sex sexual-activity,marriage/ civil unions,same-sex coupleadoptions,serving in the military,antidiscrimination laws,gender ID markers,Democracy Status,electoral process and pluralism,funct. Of gov,polit. Particpation,political culture,civil liberties,Satisfaction with GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
1,africa,6. S.Africa,Zimbabwe,C,0.42,3.16,3.692,2147,0.38,2.8,0.88,2.1,0.25,0,0,0,0,0,A,0.5,2,4.44,2.5,3.24,1.151,1.479,0.599,0.399,0.065,0.025
2,africa,6. S.Africa,Zambia,C,0.97,5.61,4.377,1539.9,0.49,3.2,0.95,2,0.25,0.33,0,0,0,0,H,6.17,4.64,3.89,5.63,4.41,0.493,1.048,0.454,0.504,0.352,0.055
3,asia,8. W. Asia,Yemen,M,0.56,1.95,3.355,944.41,1.5,4.7,0.99,7.2,0,0.33,0,0,0,0,A,0,0,3.89,5.63,3.24,0.357,1.094,0.248,0.406,0.132,0.099
4,asia,10. SE. Asia,Vietnam,x,3.89,3.08,5.103,2563.82,3.27,7.6,0.3,1.5,1,0.33,0,0.5,0,0.5,A,0,NaN,3.21,3.75,4.41,0.689,1.172,0.048,0.462,0.201,0.032
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,africa,6. S.Africa,Angola,C,3.39,3.62,3.795,3432.39,NaN,4.1,0.88,3.2,1,0.33,0,0,0.2,0.5,A,1.75,2.86,5.56,8.75,10,1.33,1.532,0.896,0.653,0.321,0.291
181,europe,18. S. Europe,Andorra,C,5.28,NaN,NaN,42029.76,NaN,2.4,NaN,0,1,0.67,0.5,0,1,0,NaN,NaN,NaN,NaN,10,9.41,1.355,1.501,0.913,0.659,0.285,0.383
182,africa,3. N.Africa,Algeria,M,1.39,3.5,5.295,4278.85,6.66,8,0.95,6.3,0.5,0.33,0,0,0,0,A,2.58,2.21,3.89,9.38,9.12,1.351,1.59,0.868,0.683,0.284,0.408
183,europe,18. S. Europe,Albania,M,4.72,5.98,4.586,5253.63,0.93,1.6,0.39,0.1,1,0.33,0,0.5,1,0,H,7,4.71,5.56,8.13,9.12,1.301,1.559,0.883,0.533,0.354,0.272
184,asia,9. C. Asia,Afghanistan,M,0.56,2.97,3.632,520.9,NaN,6.5,0.97,6.9,0,0.33,0,0,0,0,A,2.92,1.14,4.44,5.63,8.53,1.293,1.466,0.908,0.52,0.098,0.176

In [ ]:
## DF Tweets
## Fuente: https://www.kaggle.com/code/vencerlanz09/lgbt-tweets-eda-sentiment-analysis

In [14]:
df_tweets = pd.read_csv('/mnt/c/Users/arian/Documents/Adalab/Modulo 4/proyecto-da-promo-k-modulo-4-team-3/files/LGBT_Tweets_processed.csv', index_col=0)
df_tweets

,date,time,id,tweet,language,replies_count,retweets_count,likes_count
0,2022-08-26,10:31:10,1562991009180827649,Praying for my lgbt Nigerians 🙏🏽🙏🏽🙏🏽,en,0,0,0
1,2022-08-26,10:31:02,1562990976939229184,@yanmisamm So pass agg omg you really are lgbt,en,0,0,0
3,2022-08-26,10:30:59,1562990965442326528,@ChampionExcel @watokohom @MrAndyNgo @football...,en,0,0,0
7,2022-08-26,10:30:34,1562990860928659457,To be clear it doesn't justify what the LGBT c...,en,0,0,0
10,2022-08-26,10:30:24,1562990819485032449,good night lgbt community https://t.co/0PAMOU...,en,1,0,2
...,...,...,...,...,...,...,...,...
99995,2022-08-21,00:09:11,1561022541833068545,@i664k @birdofterror4 @st1mmer @cringepolitik ...,en,0,1,1
99997,2022-08-21,00:09:06,1561022522933616642,@Comrade4568 I`m anti-trans and anti-lgbt,en,1,0,1
100009,2022-08-21,00:07:52,1561022211405881344,#Lgbt #lgbtq #lgbtqiaplus #lgbtqcommunity #lgb...,en,0,0,0
100010,2022-08-21,00:07:50,1561022206167187456,Man its no fucking wonder why it's so hard for...,en,1,0,0
100017,2022-08-21,00:07:09,1561022032858464256,REPUBLICANS BRAGGING ABOUT WHAT? Legislation:...,en,0,1,0

In [ ]:
## DF Criminalizacion
## Fuente: https://www.humandignitytrust.org/lgbt-the-law/map-of-criminalisation/

In [15]:
df_criminalizacion = pd.read_csv('/mnt/c/Users/arian/Documents/Adalab/Modulo 4/proyecto-da-promo-k-modulo-4-team-3/files/Criminalizacion_LGBT.csv')
df_criminalizacion

,País,Criminaliza a personas LGBT,Criminaliza actividad sexual entre hombres,Criminaliza actividad sexual entre mujeres,Criminaliza la expresión de género de personas trans,Impone la pena de muerte,Pena máxima
0,Afganistán,Sí,Sí,Sí,No,Sí,Pena de muerte
1,Bangladés,Sí,Sí,Sí,No,No,Cadena perpetua
2,Brunéi,Sí,Sí,Sí,Sí,Sí,Muerte por lapidación
3,Indonesia,Sí,Sí,Sí,Sí,No,Ocho años de prisión y 100 latigazos
4,Irán,Sí,Sí,Sí,No,Sí,Pena de muerte
...,...,...,...,...,...,...,...
59,San Vicente y las Granadinas,Sí,Sí,Sí,NaN,NaN,Diez años de prisión
60,Trinidad y Tobago,Sí,Sí,Sí,NaN,NaN,Diez años de prisión
61,Belice,Sí,Sí,Sí,NaN,NaN,Diez años de prisión
62,Dominicana,Sí,Sí,Sí,NaN,NaN,NaN
63,Jordania,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
df_criminalizacion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 7 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   País                                                  64 non-null     object
 1   Criminaliza a personas LGBT                           63 non-null     object
 2   Criminaliza actividad sexual entre hombres            63 non-null     object
 3   Criminaliza actividad sexual entre mujeres            63 non-null     object
 4   Criminaliza la expresión de género de personas trans  59 non-null     object
 5   Impone la pena de muerte                              59 non-null     object
 6   Pena máxima                                           62 non-null     object
dtypes: object(7)
memory usage: 3.6+ KB

In [ ]:
## DF Index
## Fuente: https://ourworldindata.org/grapher/lgbt-legal-equality-index

In [19]:
df_index = pd.read_csv('/mnt/c/Users/arian/Documents/Adalab/Modulo 4/proyecto-da-promo-k-modulo-4-team-3/files/lgbt-legal-equality-index.csv')
df_index

          Entity      Code  Year   ei_legal
0    Afghanistan       AFG  2024   0.000000
1         Africa       NaN  2024  20.723385
2        Albania       ALB  2024  62.270000
3        Algeria       DZA  2024   3.420000
4        Andorra       AND  2024  85.710000
..           ...       ...   ...        ...
196      Vietnam       VNM  2024  58.180000
197        World  OWID_WRL  2024  49.721184
198        Yemen       YEM  2024   0.000000
199       Zambia       ZMB  2024  17.650000
200     Zimbabwe       ZWE  2024  33.030000

[201 rows x 4 columns]

In [20]:
df_index['Entity'].unique()

array(['Afghanistan', 'Africa', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Asia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia',
       'Cameroon', 'Canada', 'Cape Verde', 'Central African Republic',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus',
       'Czechia', 'Democratic Republic of Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'East Timor', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Europe', 'Fiji', 'Finland', 'France',
       'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece',
       'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
       'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan',
       'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait',
       'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar',
       'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia (country)', 'Moldova', 'Monaco', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'North America', 'North Korea',
       'North Macedonia', 'Norway', 'Oceania', 'Oman', 'Pakistan',
       'Palau', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia',
       'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South America',
       'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan',
       'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan',
       'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
       'Vanuatu', 'Venezuela', 'Vietnam', 'World', 'Yemen', 'Zambia',
       'Zimbabwe'], dtype=object)

In [21]:
df_omophobia.columns

Index(['COUNTRY', 'CSSSA LEGAL?', 'DATE OF DECRIM', 'MAX PENALTY', 'CONST.',
       'BROAD PROT.', 'EMPLOY.', 'HATE CRIME', 'INCITEMENT',
       'BAN CONV. THERAPIES', 'SAME SEX MARRIAGE', 'CIVIL UNIONS',
       'JOINT ADOPTION', 'SECOND PARENT ADOPTION'],
      dtype='object')

In [22]:

df_index.rename(columns={"Entity": 'COUNTRY'}, inplace=True)

In [23]:
df_index

         COUNTRY      Code  Year   ei_legal
0    Afghanistan       AFG  2024   0.000000
1         Africa       NaN  2024  20.723385
2        Albania       ALB  2024  62.270000
3        Algeria       DZA  2024   3.420000
4        Andorra       AND  2024  85.710000
..           ...       ...   ...        ...
196      Vietnam       VNM  2024  58.180000
197        World  OWID_WRL  2024  49.721184
198        Yemen       YEM  2024   0.000000
199       Zambia       ZMB  2024  17.650000
200     Zimbabwe       ZWE  2024  33.030000

[201 rows x 4 columns]

In [24]:

df_unido = pd.merge(df_index, df_omophobia, on='COUNTRY', how='outer', indicator=True)

# Ver los países que están solo en df1
solo_en_df_index = df_unido[df_unido['_merge'] == 'left_only']

# Ver los países que están solo en df2
solo_en_df_omophobia = df_unido[df_unido['_merge'] == 'right_only']

# Ver los países comunes en ambos DataFrames
mismos_paises = df_unido[df_unido['_merge'] == 'both']

In [30]:
mismos_paises.head(5)

,COUNTRY,Code,Year,ei_legal,CSSSA LEGAL?,DATE OF DECRIM,MAX PENALTY,CONST.,BROAD PROT.,EMPLOY.,HATE CRIME,INCITEMENT,BAN CONV. THERAPIES,SAME SEX MARRIAGE,CIVIL UNIONS,JOINT ADOPTION,SECOND PARENT ADOPTION,_merge
0,Afghanistan,AFG,2024.0,0.00,NO,-,DEATH (P),NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both
2,Albania,ALB,2024.0,62.27,YES,1995,-,NO,YES,YES,YES,YES,NO,NO,NO,NO,NO,both
3,Algeria,DZA,2024.0,3.42,NO,-,2,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both
5,Andorra,AND,2024.0,85.71,YES,1990,-,NO,YES,YES,YES,NO,NO,NO,YES,YES,YES,both
6,Angola,AGO,2024.0,66.19,YES,2021,-,NO,YES,YES,YES,YES,NO,NO,NO,NO,NO,both

In [28]:
solo_en_df_omophobia.head(5)

,COUNTRY,Code,Year,ei_legal,CSSSA LEGAL?,DATE OF DECRIM,MAX PENALTY,CONST.,BROAD PROT.,EMPLOY.,HATE CRIME,INCITEMENT,BAN CONV. THERAPIES,SAME SEX MARRIAGE,CIVIL UNIONS,JOINT ADOPTION,SECOND PARENT ADOPTION,_merge
4,American Samoa (USA),NaN,NaN,NaN,YES,1980,-,NaN,NO,NO,NO,NO,NO,NO,NO,NO,NO,right_only
7,Anguilla (UK),NaN,NaN,NaN,YES,2001,-,NaN,NO,NO,LIMITED,NO,NO,NO,NO,NO,NO,right_only
11,Aruba (NL),NaN,NaN,NaN,YES,1869,-,NaN,YES,YES,NO,YES,NO,NO,YES,NO,NO,right_only
24,Bermuda (UK),NaN,NaN,NaN,YES,1994,-,NaN,YES,YES,YES,YES,NO,NO,NO,YES,YES,right_only
27,Bonaire (NL),NaN,NaN,NaN,YES,1869,-,NaN,YES,YES,NO,YES,NO,YES,YES,NO,NO,right_only

In [29]:
solo_en_df_index.head(5)

,COUNTRY,Code,Year,ei_legal,CSSSA LEGAL?,DATE OF DECRIM,MAX PENALTY,CONST.,BROAD PROT.,EMPLOY.,HATE CRIME,INCITEMENT,BAN CONV. THERAPIES,SAME SEX MARRIAGE,CIVIL UNIONS,JOINT ADOPTION,SECOND PARENT ADOPTION,_merge
1,Africa,NaN,2024.0,20.723385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
12,Asia,NaN,2024.0,48.204490,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
29,Bosnia and Herzegovina,BIH,2024.0,63.330000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
34,Brunei,BRN,2024.0,6.830000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
43,Cape Verde,CPV,2024.0,51.220000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [32]:
df_unido

,COUNTRY,Code,Year,ei_legal,CSSSA LEGAL?,DATE OF DECRIM,MAX PENALTY,CONST.,BROAD PROT.,EMPLOY.,HATE CRIME,INCITEMENT,BAN CONV. THERAPIES,SAME SEX MARRIAGE,CIVIL UNIONS,JOINT ADOPTION,SECOND PARENT ADOPTION,_merge
0,Afghanistan,AFG,2024.0,0.000000,NO,-,DEATH (P),NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both
1,Africa,NaN,2024.0,20.723385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,Albania,ALB,2024.0,62.270000,YES,1995,-,NO,YES,YES,YES,YES,NO,NO,NO,NO,NO,both
3,Algeria,DZA,2024.0,3.420000,NO,-,2,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both
4,American Samoa (USA),NaN,NaN,NaN,YES,1980,-,NaN,NO,NO,NO,NO,NO,NO,NO,NO,NO,right_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256,Wallis and Futuna (FR),NaN,NaN,NaN,YES,NEVER CRIM,-,NaN,YES,YES,YES,YES,NO,YES,YES,YES,YES,right_only
257,World,OWID_WRL,2024.0,49.721184,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
258,Yemen,YEM,2024.0,0.000000,NO,-,DEATH,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both
259,Zambia,ZMB,2024.0,17.650000,NO,-,FOR LIFE,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both
260,Zimbabwe,ZWE,2024.0,33.030000,NO,-,1,NO,NO,NO,NO,NO,NO,NO,NO,NO,NO,both